version: "2"

services:
  hashtranslator:
    container_name: hashtranslator-service
    build:
      context: hashtranslator-service
    restart: on-failure
    depends_on: 
      - mongodb
      - authorization
    ports:
      - "8082:8080"
    environment:
      MONGODB_URL: mongodb://mongodb:27017/application_store
      AUTH_SERVICE_URL: http://authorization:8080
      MD5DECRYPT_URL: https://md5decrypt.net/en/Api/api.php
      MD5DECRYPT_EMAIL: aliakse.kryzhanouski@gmail.com
      MD5DECRYPT_CODE: d28479976da99c11
  authorization:
    container_name: authorization-service
    build:
      context: authorization-service
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_store
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      CONFIG_ADMIN_EMAIL: admin@admin.com
      CONFIG_ADMIN_PASSWORD: admin
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - auth_pgdata:/var/lib/postgresql/auth_pgdata
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - auth_pgadmin:/var/lib/auth_pgadmin
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27000:27017"    
    volumes:
      - hash_mongodb:/var/lib/hash_mongodb
        
volumes:
  auth_pgdata:
  auth_pgadmin:
  hash_mongodb: