spring:
  application:
    name: hash-translator
  data:
    mongodb:
      uri: ${MONGODB_URL}
feign:
  client:
    config:
      auth-service:
        error-decoder: tt.hashtranslator.client.authorization.AuthorizationErrorDecoder
        read-timeout: 300000


service:
  authorization:
    url: ${AUTH_SERVICE_URL}
  md5-decrypt:
    url: ${MD5_DECRYPT_SERVICE_URL}
      
