spring:
  application:
    name: hash-translator
  data:
    mongodb:
      uri: ${MONGODB_URL}
feign:
  client:
    config:
      auth-service:
        error-decoder: tt.hashtranslator.api.authorization.AuthorizationErrorDecoder
        read-timeout: 300000


service:
  authorization:
    url: ${AUTH_SERVICE_URL}
  translator:
    md5decrypt:
      uri: ${MD5DECRYPT_URL}
      email: ${MD5DECRYPT_EMAIL}
      code: ${MD5DECRYPT_CODE}
      hash_type: md5
      hash_per_request: 400
      
