spring:
  application:
    name: hash-translator
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: application_store

service:
  authorization:
    url: http://authorization:8080/api/login
  translator:
    md5decrypt:
      hash_type: md5
      email: aliaksei.kryzhanouski@gmail.com
      code: d28479976da99c11
      uri: https://md5decrypt.net/en/Api/api.php
      hash_per_request: 400
